import os
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, GroupAction, IncludeLaunchDescription
from launch.launch_description_sources import PythonLaunchDescriptionSource
from ament_index_python.packages import get_package_share_directory
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node, PushRosNamespace

def generate_launch_description():
    declared_arguments = [
        DeclareLaunchArgument('camera_name', default_value='camera'),
        DeclareLaunchArgument('depth_registration', default_value='true'),
        DeclareLaunchArgument('serial_number', default_value=''),
        DeclareLaunchArgument('device_num', default_value='1'),
        DeclareLaunchArgument('vendor_id', default_value='0'),
        DeclareLaunchArgument('product_id', default_value='0'),
        DeclareLaunchArgument('enable_point_cloud', default_value='true'),
        DeclareLaunchArgument('enable_colored_point_cloud', default_value='false'),
        DeclareLaunchArgument('point_cloud_qos', default_value='default'),
        DeclareLaunchArgument('connection_delay', default_value='100'),
        DeclareLaunchArgument('color_width', default_value='640'),
        DeclareLaunchArgument('color_height', default_value='480'),
        DeclareLaunchArgument('color_fps', default_value='30'),
        DeclareLaunchArgument('enable_color', default_value='true'),
        DeclareLaunchArgument('flip_color', default_value='false'),
        DeclareLaunchArgument('color_qos', default_value='default'),
        DeclareLaunchArgument('color_camera_info_qos', default_value='default'),
        DeclareLaunchArgument('depth_width', default_value='640'),
        DeclareLaunchArgument('depth_height', default_value='480'),
        DeclareLaunchArgument('depth_fps', default_value='30'),
        DeclareLaunchArgument('enable_depth', default_value='true'),
        DeclareLaunchArgument('flip_depth', default_value='false'),
        DeclareLaunchArgument('depth_qos', default_value='default'),
        DeclareLaunchArgument('depth_camera_info_qos', default_value='default'),
        DeclareLaunchArgument('ir_width', default_value='640'),
        DeclareLaunchArgument('ir_height', default_value='480'),
        DeclareLaunchArgument('ir_fps', default_value='30'),
        DeclareLaunchArgument('enable_ir', default_value='true'),
        DeclareLaunchArgument('flip_ir', default_value='false'),
        DeclareLaunchArgument('ir_qos', default_value='default'),
        DeclareLaunchArgument('ir_camera_info_qos', default_value='default'),
        DeclareLaunchArgument('publish_tf', default_value='true'),
        DeclareLaunchArgument('tf_publish_rate', default_value='10.0'),
        DeclareLaunchArgument('ir_info_url', default_value=''),
        DeclareLaunchArgument('color_info_url', default_value=''),
        DeclareLaunchArgument('color_roi_x', default_value='-1'),
        DeclareLaunchArgument('color_roi_y', default_value='-1'),
        DeclareLaunchArgument('color_roi_width', default_value='-1'),
        DeclareLaunchArgument('color_roi_height', default_value='-1'),
        DeclareLaunchArgument('depth_roi_x', default_value='-1'),
        DeclareLaunchArgument('depth_roi_y', default_value='-1'),
        DeclareLaunchArgument('depth_roi_width', default_value='-1'),
        DeclareLaunchArgument('depth_roi_height', default_value='-1'),
        DeclareLaunchArgument('depth_scale', default_value='1'),
        DeclareLaunchArgument('color_depth_synchronization', default_value='true'),
        DeclareLaunchArgument('use_uvc_camera', default_value='true'),
        DeclareLaunchArgument('uvc_vendor_id', default_value='0x2bc5'),
        DeclareLaunchArgument('uvc_product_id', default_value='0x0501'),
        DeclareLaunchArgument('uvc_retry_count', default_value='100'),
        DeclareLaunchArgument('uvc_camera_format', default_value='mjpeg'),
        DeclareLaunchArgument('uvc_flip', default_value='false'),
        DeclareLaunchArgument('oni_log_level', default_value='verbose'),
        DeclareLaunchArgument('oni_log_to_console', default_value='false'),
        DeclareLaunchArgument('oni_log_to_file', default_value='false'),
        DeclareLaunchArgument('enable_d2c_viewer', default_value='false'),
        DeclareLaunchArgument('enable_publish_extrinsic', default_value='false'),
    ]

    camera_name = LaunchConfiguration('camera_name')

    node = Node(
        package='astra_camera',
        executable='astra_camera_node',
        name='camera',
        output='screen',
        parameters=[{
            'camera_name': LaunchConfiguration('camera_name'),
            'depth_registration': LaunchConfiguration('depth_registration'),
            'serial_number': LaunchConfiguration('serial_number'),
            'device_num': LaunchConfiguration('device_num'),
            'vendor_id': LaunchConfiguration('vendor_id'),
            'product_id': LaunchConfiguration('product_id'),
            'enable_point_cloud': LaunchConfiguration('enable_point_cloud'),
            'enable_colored_point_cloud': LaunchConfiguration('enable_colored_point_cloud'),
            'point_cloud_qos': LaunchConfiguration('point_cloud_qos'),
            'connection_delay': LaunchConfiguration('connection_delay'),
            'color_width': LaunchConfiguration('color_width'),
            'color_height': LaunchConfiguration('color_height'),
            'color_fps': LaunchConfiguration('color_fps'),
            'enable_color': LaunchConfiguration('enable_color'),
            'flip_color': LaunchConfiguration('flip_color'),
            'color_qos': LaunchConfiguration('color_qos'),
            'color_camera_info_qos': LaunchConfiguration('color_camera_info_qos'),
            'depth_width': LaunchConfiguration('depth_width'),
            'depth_height': LaunchConfiguration('depth_height'),
            'depth_fps': LaunchConfiguration('depth_fps'),
            'enable_depth': LaunchConfiguration('enable_depth'),
            'flip_depth': LaunchConfiguration('flip_depth'),
            'depth_qos': LaunchConfiguration('depth_qos'),
            'depth_camera_info_qos': LaunchConfiguration('depth_camera_info_qos'),
            'ir_width': LaunchConfiguration('ir_width'),
            'ir_height': LaunchConfiguration('ir_height'),
            'ir_fps': LaunchConfiguration('ir_fps'),
            'enable_ir': LaunchConfiguration('enable_ir'),
            'flip_ir': LaunchConfiguration('flip_ir'),
            'ir_qos': LaunchConfiguration('ir_qos'),
            'ir_camera_info_qos': LaunchConfiguration('ir_camera_info_qos'),
            'publish_tf': LaunchConfiguration('publish_tf'),
            'tf_publish_rate': LaunchConfiguration('tf_publish_rate'),
            'ir_info_url': LaunchConfiguration('ir_info_url'),
            'color_info_url': LaunchConfiguration('color_info_url'),
            'color_roi_x': LaunchConfiguration('color_roi_x'),
            'color_roi_y': LaunchConfiguration('color_roi_y'),
            'color_roi_width': LaunchConfiguration('color_roi_width'),
            'color_roi_height': LaunchConfiguration('color_roi_height'),
            'depth_roi_x': LaunchConfiguration('depth_roi_x'),
            'depth_roi_y': LaunchConfiguration('depth_roi_y'),
            'depth_roi_width': LaunchConfiguration('depth_roi_width'),
            'depth_roi_height': LaunchConfiguration('depth_roi_height'),
            'depth_scale': LaunchConfiguration('depth_scale'),
            'color_depth_synchronization': LaunchConfiguration('color_depth_synchronization'),
            'use_uvc_camera': LaunchConfiguration('use_uvc_camera'),
            'uvc_vendor_id': LaunchConfiguration('uvc_vendor_id'),
            'uvc_product_id': LaunchConfiguration('uvc_product_id'),
            'uvc_retry_count': LaunchConfiguration('uvc_retry_count'),
            'uvc_camera_format': LaunchConfiguration('uvc_camera_format'),
            'uvc_flip': LaunchConfiguration('uvc_flip'),
            'oni_log_level': LaunchConfiguration('oni_log_level'),
            'oni_log_to_console': LaunchConfiguration('oni_log_to_console'),
            'oni_log_to_file': LaunchConfiguration('oni_log_to_file'),
            'enable_d2c_viewer': LaunchConfiguration('enable_d2c_viewer'),
            'enable_publish_extrinsic': LaunchConfiguration('enable_publish_extrinsic'),
        }],
        remappings=[
            ('/camera/depth/color/points', '/camera/depth_registered/points'),
        ],
    )

    color_compressed = Node(
        package='image_transport',
        executable='republish',
        name='color_compressed',
        namespace=LaunchConfiguration('camera_name'),
        output='screen',
        arguments=['raw', 'compressed'],
        remappings=[
            ('in', '/camera_rear/color/image_raw'),
            ('out/compressed', '/camera_rear/color/image_raw/compressed'),
        ],
    )

    depth_compressed = Node(
        package='image_transport',
        executable='republish',
        name='depth_compressed',
        namespace=LaunchConfiguration('camera_name'),
        output='screen',
        arguments=['raw', 'compressedDepth'],
        remappings=[
            ('in', '/camera_rear/depth/image_raw'),
            ('out/compressedDepth', '/camera_rear/depth/image_raw/compressedDepth'),
        ],
    )

    return LaunchDescription(
        declared_arguments + [
            GroupAction([
                PushRosNamespace(camera_name),
                node,
            ]),
            color_compressed,
            depth_compressed,
        ]
    )